SELECT CONCAT(NAME, '(', LEFT(OCCUPATION, 1), ')') AS FULL_NAME from OCCUPATIONS ORDER BY NAME asc;
SELECT CONCAT('There are a total of ', COUNT(OCCUPATION),' ', LOWER(OCCUPATION),'s.') as TOTAL from OCCUPATIONS group by OCCUPATION order by TOTAL
