SELECT H1.HACKER_ID, H1.NAME, COUNT(CH1.CHALLENGE_ID) as TOTAL_COUNT
from HACKERS H1 JOIN CHALLENGES CH1
ON H1.HACKER_ID = CH1.HACKER_ID
GROUP BY H1.HACKER_ID, H1.NAME
HAVING TOTAL_COUNT = 
(
SELECT COUNT(CH2.CHALLENGE_ID) as MAX_COUNT
    from CHALLENGES CH2
    GROUP BY CH2.HACKER_ID
    ORDER BY MAX_COUNT DESC
    LIMIT 1
)
OR TOTAL_COUNT IN
(
    SELECT DISTINCT OTHER_COUNTS from (
SELECT H2.HACKER_ID, H2.NAME, COUNT(CH2.CHALLENGE_ID) AS OTHER_COUNTS
from HACKERS H2 JOIN CHALLENGES CH2
on H2.HACKER_ID = CH2.HACKER_ID
GROUP BY H2.HACKER_ID, H2.NAME
) subquery
    GROUP BY OTHER_COUNTS
HAVING COUNT(OTHER_COUNTS) =1)
ORDER BY TOTAL_COUNT DESC, H1.HACKER_ID
