SELECT M.HACKER_ID,
(SELECT H.NAME from HACKERS H WHERE H.HACKER_ID = M.HACKER_ID) AS NAME,
SUM(M.SCORE) AS TOTAL_SCORE from
(SELECT HACKER_ID, MAX(SCORE) SCORE FROM SUBMISSIONS S
   GROUP BY 1, S.CHALLENGE_ID) M 
GROUP BY 1
HAVING TOTAL_SCORE > 0
ORDER BY TOTAL_SCORE DESC, HACKER_ID;
